[Signalement] Ajout du champ date
MTES-MCT/monitorenv pull request #1051
Opened 2023-12-08 09:58 UTC by claire2212

## Related Pull Requests & Issues

- Resolve #1040

Emplacement validé avec Adeline : 

<img width="515" alt="Capture d’écran 2023-12-18 à 12 13 02" src="https://github.com/MTES-MCT/monitorenv/assets/23258718/11406328-e717-4baf-a158-31db253e5bdf">

----

- [x] Tests E2E (Cypress)

2023-12-19 09:59 UTC, thoomasbro commented on frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
> +  const createdAt = values.createdAt || customDayjs().toISOString()
createdAt est déjà set, non?

2023-12-19 14:34 UTC, claire2212 commented on frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
> +  const createdAt = values.createdAt || customDayjs().toISOString()
tu peux supprimer la valeur du champ, et dans ce cas ça plante

2023-12-21 11:31 UTC, thoomasbro commented on frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
> +  const createdAt = values.createdAt || customDayjs().toISOString()
dans ce cas je pense qu'il faut changer le typing de `createdAt` qui peut être undefined dans `domain/entities/reporting.ts`

2023-12-21 13:36 UTC, claire2212 commented on frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
> +  const createdAt = values.createdAt || customDayjs().toISOString()
non car le champ est obligatoire pour enregistrer le signalement

2023-12-21 16:52 UTC, thoomasbro commented on frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
> +  const createdAt = values.createdAt || customDayjs().toISOString()
oui mais ça c'est géré dans la validation, non? Dans les faits, si on supprime la date dans le `FormikDatePicker`, `createdAt` est bien undefined, et TS ne le voit pas puisque ce n'est pas du typing à l'exécution. Mettre `createdAt` à `string | undefined` permet d'identifier d'autres endroits où il y a possiblement des bugs (Réouverture dans le footer par exemple, bien que ce soit vraiment improbable comme cas). Je serais plutot partant pour changer le type, à moins que tu penses que ça soit vraiment incohérent.

2023-12-22 08:27 UTC, claire2212 commented on frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
> +  const createdAt = values.createdAt || customDayjs().toISOString()
ok

2024-01-03 13:41 UTC, louptheron approved these changes

2024-01-03 13:41 UTC, louptheron commented on frontend/cypress/e2e/side_window/reporting/create_reporting.spec.ts
> +    cy.intercept('PUT', '/bff/v1/reportings', FAKE_API_PUT_RESPONSE).as('createReporting')
Je dirais que l'idéal (pas forcément dans cette PR) serait de ne pas stubber cee call, mais de revert les changements dans le test par la suite. Cela nous permet d'avoir des tests E2E qui valident le scénario full-stack

2024-01-03 13:51 UTC, merged

2024-01-03 14:08 UTC, ivangabriele requested changes

2024-01-03 14:16 UTC, claire2212 commented on frontend/src/App.tsx
> +  // expose store when run in Cypress
j'utilise effectivement des actions dans cypress. Notamment pour renseigner des zones de missions ou point de signalement (interaction avec la map impossible)