[Zone de vigilance] création du formulaire + consultation de la zone de vigilance
MTES-MCT/monitorenv pull request #1514
Opened 2024-06-28 06:59 UTC by claire2212

## Related Pull Requests & Issues

- Resolve #1477

----

- [ ] Tests E2E (Cypress)

2024-07-02 07:18 UTC, claire2212 commented on frontend/src/utils/utils.ts
> +const vigilanceAreaColors = [
on met les couleurs de AMP pour les zones de vigilances + nouvelles couleurs pour les AMP

2024-07-02 07:20 UTC, claire2212 commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/vigilanceArea/VigilanceAreaEntity.kt
> +    val endDatePeriod: ZonedDateTime? = null,
pour les dates je n'ai pas mis le ` utc` dans le nom de la propriété comme on fait d'habitude. Je veux bien votre avis

2024-07-02 07:23 UTC, claire2212 commented on frontend/.env.example
> +FRONTEND_VIGILANCE_AREA_ENBALED=true
Ajout du feature flag pour pouvoir mettre en prod au fur et à mesure

2024-07-02 07:25 UTC, claire2212 commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/DrawVigilanceArea.tsx
> +export function DrawVigilanceArea() {
comme on doit afficher les boutons dans le formulaire, j'ai recréé l'équivalent du composant DrawModal, en plus simple. La geom est stockée dans un store, mais vient se mettre à jour dans le formulaire, seulement quand on clique sur "Valider les tracés"

2024-07-02 07:32 UTC, claire2212 commented on frontend/src/features/VigilanceArea/slice.ts
> +  SELECT_AMP = 'SELECT_AMP',
`SELECT_AMP` et `SELECT_REGULATORY` seront utilisés plus tard pour la sélection d'AMP ou de zones réglementaires en lien avec la zone de vigilance

2024-07-03 15:46 UTC, maximeperraultdev requested changes

2024-07-03 15:46 UTC, maximeperraultdev commented on frontend/src/features/commonComponents/ZonePicker/index.tsx
> +          <Row key={`zone-${index}`}>
issue: pas d'index, il m'est déjà arrivé des dingueries

2024-07-03 15:46 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/vigilanceAreaGeometryHelper.ts
> +  feature.setProperties({
question : vu que c'est le mêmes propriétés tu peux utiliser le spread operator non ?

2024-07-03 15:46 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/index.tsx
> +    const test = vigilanceAreas
nitpick: un petit oubli ? tu peux retourner directement le tableau

2024-07-03 15:46 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/VigilanceAreaPanel.tsx
> +      PublishedSchema.validateSync(values, { abortEarly: false })
question: ça jette une erreur si le formulaire est invalide ? ça me parait violent quand meme

2024-07-03 15:46 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Links.tsx
> +  const [isCreatingLink, setIsCreatingLink] = useState<number | undefined>(undefined)
suggestion: Je pense qu'il faudrait. faire apparaitre le fait que ce soit un index (ca fait bizarre à la ligne 37)

2024-07-03 15:46 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/types.ts
> +export namespace VigilanceArea {
Question: Est-ce que tu serais prête à essayer les strings literals sur ce fichier ?

2024-07-04 09:14 UTC, claire2212 commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/vigilanceArea/CreateOrUpdateVigilanceArea.kt
> +    @Throws(IllegalArgumentException::class)
je l'enlève ça ne sert effectivement à rien

2024-07-04 09:45 UTC, claire2212 commented on backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/VigilanceAreasITests.kt
> +            .andExpect(jsonPath("$[0].geom.type", equalTo("MultiPolygon")))
j'ajoute ce qu'il manque

2024-07-04 12:48 UTC, claire2212 commented on frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/index.tsx
> +    const test = vigilanceAreas
oups

2024-07-04 12:51 UTC, claire2212 commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/VigilanceAreaPanel.tsx
> +      PublishedSchema.validateSync(values, { abortEarly: false })
c'est comme ça que fonctionne la fonction elle throw une erreur si le schéma est invalide

2024-07-04 13:16 UTC, claire2212 commented on frontend/src/features/VigilanceArea/types.ts
> +export namespace VigilanceArea {
les enum sont utiles ici, pour créer les options dans les sélecteurs du formulaire. On a une fonction qui fait ça tout seul, donc je préfère rester avec les enume

2024-07-04 13:57 UTC, maximeperraultdev approved these changes

2024-07-05 05:27 UTC, merged