[Zone de vigilance] Pouvoir filtrer les zones de vigilance par période
MTES-MCT/monitorenv pull request #1590
Opened 2024-07-30 12:35 UTC by claire2212

## Related Pull Requests & Issues

- Resolve #1586

----

- [ ] Tests E2E (Cypress)

2024-08-01 15:26 UTC, maximeperraultdev requested changes

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/useCases/saveVigilanceArea.ts
> +          return undefined // No recurrence
suggestion : Il n'y a pas de date de fin calculé si jamais on a pas de fréquence ? J'aurais mis un break et fais comme si il n'y avait rien

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/search/LayerFilters.tsx
> +  const handleSetFilteredRegulatoryThemes = nextRegulatoryThemes => {
🙏 merci ! Mais le typage 🤔 🥲 ?

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/search/ResultsList/VigilanceAreaLayer/index.tsx
> -        {layer?.name ?? 'AUCUN NOM'}
question / todo : Je crois que il y a le même probleme de doublon sur les autres listes. On peut le faire dans un autre ticket si ça te saoule =)

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/search/hooks/useSearchLayers.ts
> +            vigilanceAreasPerPeriod.length > 0 && vigilanceAreaPeriodFilter
suggestion : pas besoin de vérifier la taille de vigilanceAreasPerPeriod, `include` renverra false de toute facon

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/search/index.tsx
> +  const handleSetFilteredVigilanceAreaPeriod = nextVigilanceAreaPeriod => {
todo : :cought: le typage s'il te plaît :cought:

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts
> +      endDatePeriod: `${customDayjs().format('YYYY-MM-DD')} 23:59:59.99999`, // today + 30 days
```suggestion
      endDatePeriod: `${customDayjs().format('YYYY-MM-DD')} 23:59:59.99999`, // end of day
```

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts
> +      endingOccurrencesNumber: undefined,
question: ça ne devrait pas etre `12` si la fréquence est tout les mois et que ça finit l'année prochaine ?

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts
> +    expect(result).toEqual([areas[0], areas[1], areas[2]])
suggestion: avoir des assertions un peu plus différents dans les tests

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts
> +function isWithinPeriod(date, startDate, endDate) {
todo: le typage svp

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts
> +        startDateFilter = now.utc().startOf('quarter')
oh ! c'est pratique ça.

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts
> +      startDate &&
suggestion: `startDate` & `endDate` ne peuvent etre `falsy`

2024-08-01 15:26 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts
> +            return false
suggestion : je mettrais juste un break pour laisser le `return false`juste après.

2024-08-01 15:49 UTC, maximeperraultdev approved these changes

2024-08-01 15:57 UTC, claire2212 commented on frontend/src/features/VigilanceArea/useCases/saveVigilanceArea.ts
> +  let currentOccurrence = customDayjs(vigilanceArea.startDatePeriod)
je trouve que le fait d'avoir mis `currentOccurrence` permet de mieux comprendre que c'est quelque chose qui bouge (on vient mettre à jour la variable suivant les récurrence). Ca ne correspond pas à la date de début de vigilance (à part quand on l'initialise)

2024-08-01 15:58 UTC, claire2212 commented on frontend/src/features/VigilanceArea/useCases/saveVigilanceArea.ts
> +    vigilanceArea.startDatePeriod && vigilanceArea.endDatePeriod
tu peux enregistrer une zone de vigilance sans date (en mode brouillon)

2024-08-01 16:05 UTC, claire2212 commented on frontend/src/features/VigilanceArea/useCases/saveVigilanceArea.ts
> +          return undefined // No recurrence
j'ai fais la modif de ton commentaire précédent (qui est en rapport avec ce retour). Dans le cas où il n'y a pas de récurrence la date de fin calculée vaut `vigilanceArea.endDatePeriod`

2024-08-01 16:09 UTC, claire2212 commented on frontend/src/features/layersSelector/search/ResultsList/VigilanceAreaLayer/index.tsx
> -        {layer?.name ?? 'AUCUN NOM'}
oups, je corrige

2024-08-01 16:16 UTC, claire2212 commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts
> +    expect(result).toEqual([areas[0], areas[1], areas[2]])
c'est à dire?

2024-08-01 16:18 UTC, claire2212 commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts
> +      startDate &&
j'ai ajouté de `!!`

2024-08-01 16:21 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts
> +    expect(result).toEqual([areas[0], areas[1], areas[2]])
les assertions des 3 derniers tests sont les mêmes. Je pense que ca vaut le coup de mettre des valeurs plus différentes

2024-08-01 16:22 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/useCases/saveVigilanceArea.ts
> +    vigilanceArea.startDatePeriod && vigilanceArea.endDatePeriod
Du coup il faut changer le typage de `VigilanceArea`

2024-08-01 16:22 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts
> +      startDate &&
Je voulais dire que d'apres le typage startDate et endDate ne peuvent pas être `falsy`. Il faut revoir le typage ou retirer la condition ^^

2024-08-01 16:23 UTC, maximeperraultdev approved these changes

2024-08-01 16:32 UTC, maximeperraultdev commented on frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts
> +      endingOccurrencesNumber: undefined,
J'ai du mal à comprendre le test alors

2024-08-02 06:35 UTC, claire2212 commented on frontend/src/features/VigilanceArea/useCases/saveVigilanceArea.ts
> +    vigilanceArea.startDatePeriod && vigilanceArea.endDatePeriod
j'ai ajouté des undefined

2024-08-02 07:06 UTC, merged