[Fiche Unité] Améliorations UI
MTES-MCT/monitorenv pull request #1653
Opened 2024-08-28 14:38 UTC by claire2212

## Related Pull Requests & Issues

- Resolve #1651

----

- [ ] Tests E2E (Cypress)

2024-08-29 14:34 UTC, maximeperraultdev requested changes
Issue: Je viens de remarquer deux pbs visuelles. 

1) Quand les champs sont en erreur ya un décalage (C'est pour ça que j'avais mis `align-items: start`)
![Capture d’écran 2024-08-29 à 16 32 34](https://github.com/user-attachments/assets/cf8dc2ba-9ee0-4ab8-9941-604a0bc815b2)
2) Quand tu saisies un long nom personnalisé
![Capture d’écran 2024-08-29 à 16 31 04](https://github.com/user-attachments/assets/e1dfabf5-c306-45a0-ac91-31344696c0b3)

2024-08-29 15:16 UTC, claire2212 commented on frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx
> +  overflow-wrap: anywhere;
je n'ai pas mis `  word-break: break-word;` car il est déprécié

2024-09-03 08:54 UTC, maximeperraultdev approved these changes

2024-09-03 08:54 UTC, maximeperraultdev commented on frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/FieldWithButton.tsx
> +  align-items: ${p => (p.$hasError ? 'center' : 'end')};
Suggestion : Ca fonctionne mais je pense qu'il y a plus simple. Il faut retirer `> .Element-IconButton` en `> div > .Element-IconButton` ou `.Element-IconButton`

2024-09-03 08:54 UTC, maximeperraultdev commented on frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/FormikNameSelect.tsx
> +  align-items: end;
idem ici

2024-09-03 09:18 UTC, merged