[Zone de vigilance] Pouvoir ajouter des images à une zone de vigilance
MTES-MCT/monitorenv pull request #1705
Opened 2024-09-18 06:51 UTC by claire2212

## Related Pull Requests & Issues

- Resolve #1643

----

- [ ] Tests E2E (Cypress)

2024-09-18 15:20 UTC, maximeperraultdev requested changes

2024-09-18 15:20 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/PhotoUploader.tsx
> +                aria-hidden="true"
issue : si tu met aria-hidden la liseuse ne fonctionnera plus et je ne pense pas que ces images soient purement décoratives.
Il faudrait que le alt corresponde à la description de l'image

2024-09-18 15:20 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/PhotoUploader.tsx
> +    cursor: zoom-in;
suggestion: tu peux ajouter `object-fit: contain` ou `cover` pour que l'image ne soit pas écrasée en fonction de sa taille de base

2024-09-18 15:20 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/VigilanceAreaPanel.tsx
> +    cursor: zoom-in;
idem pour le object-fit

2024-09-18 15:20 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/PhotoUploader.tsx
> +const PreviewImagesContainer = styled.div`
suggestion:
```suggestion
const PreviewImagesContainer = styled.li`
```

2024-09-18 15:20 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/PhotoUploader.tsx
> +const PreviewList = styled.div`
```suggestion
const PreviewList = styled.ul`
list-style: none;
padding: 0;
```

2024-09-18 15:25 UTC, maximeperraultdev requested changes

2024-09-18 15:25 UTC, maximeperraultdev commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/vigilanceArea/ImageEntity.kt
> +@Serializable
todo: Je ne pense pas que `@Serializable` soit necessaire ici car on ne le transforme pas en json

2024-09-18 15:29 UTC, claire2212 commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/ImageViewer.tsx
> +    <>
il est utile (on a le composantWrapper et le composant Background au même niveau)

2024-09-18 15:32 UTC, claire2212 commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/PhotoUploader.tsx
> +                aria-hidden="true"
je vois mal comment je peux faire en sorte que le `alt` corresponde à l'image sachant que c'est le cacem qui ajoute les images. Ca demanderait d'ajouter un champ à remplir pour renseignée cette balise.
Je peux mettre une description générique

2024-09-18 15:38 UTC, maximeperraultdev commented on frontend/src/features/VigilanceArea/components/VigilanceAreaForm/PhotoUploader.tsx
> +                aria-hidden="true"
Je me doutais que tu répondrais ça. Tu penses que c'est possible de mettre nom de la zdv + le nom de fichier. Si on met une liste on a déjà le numéro de l'image par la liseuse

2024-09-18 16:31 UTC, maximeperraultdev commented on frontend/src/hooks/useEscapeKey.ts
> +export const useEscapeKey = ({ onArrowLeft, onArrowRight, onEscape }: UseEscapeKeyProps) => {
nitpick: je voyais plutot un param de type eventKey et tu peux mettre ce que tu veux mais ça me va comme ça ^^

2024-09-18 16:31 UTC, maximeperraultdev commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/vigilanceArea/VigilanceAreaDataInput.kt
>      val links: List<LinkEntity>? = null,
todo: il y a aussi `LinkEntity` le meme souci. sorry

2024-09-18 17:03 UTC, maximeperraultdev approved these changes

2024-09-19 06:42 UTC, claire2212 commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/vigilanceArea/VigilanceAreaDataInput.kt
>      val links: List<LinkEntity>? = null,
pourquoi LinkEntity? C'est pas un input mais bien une entité

2024-09-19 07:06 UTC, maximeperraultdev commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/vigilanceArea/VigilanceAreaDataInput.kt
>      val links: List<LinkEntity>? = null,
Comment ça ? Pour moi si ton objet vient de "l'exterieur" c'est un input 🤔

2024-09-19 08:59 UTC, merged