[DATA]: Ne plus supprimer et remplacer les zones réglementaires
MTES-MCT/monitorenv pull request #1886
Opened 2024-11-26 09:36 UTC by maximeperraultdev

Le but est de ne pas supprimer les données à modifier car elles ont des clés étrangères avec d'autres tables. 

TODO: Faire les amps quand les zones réglementaires seront fonctionnelles

2024-12-03 09:36 UTC, claire2212 commented on datascience/src/pipeline/flows/regulations.py
> +        new_amp,
`new_amp` ?

2024-12-03 09:36 UTC, claire2212 commented on datascience/src/pipeline/queries/cross/cacem/regulations.sql
> +  st_multi(ST_SimplifyPreserveTopology(ST_CurveToLine(geom), 0.0001)) geom,
A supprimer, comme vu ensemble on perd beaucoup trop en détails

2024-12-03 10:09 UTC, VincentAntoine requested changes
Petites modifs à faire dans les tests pour éviter les flaky, sinon ça me semble bien !

2024-12-03 10:09 UTC, VincentAntoine commented on datascience/src/pipeline/flows/amp_cacem.py
>          df_id_column="id",
Il n'y pas besoin de `table_id_column` ni de `df_id_column` quand `how="append"`

2024-12-03 10:09 UTC, VincentAntoine commented on datascience/tests/test_pipeline/test_flows/test_regulations.py
> +def test_load_new_regulations(old_regulations):
Il faut inclure `reset_test_data` dans les inputs de la fonction `test_load_new_regulations` sinon les données ne sont pas reset avant le test, ce qui est la porte ouverte aux flaky tests :)

2024-12-03 10:09 UTC, VincentAntoine commented on datascience/tests/test_pipeline/test_flows/test_regulations.py
> +def test_update_new_regulations(new_regulations):
Idem, et ici ça fonctionne "par chance" parce que les données `old_regulations` ont été insérées dans le test précédent, mais l'ordre d'exécution n'est pas garanti donc il faut mettre `reset_test_data` dans le test (ce qui va supprimer les données éventuellement insérées par un test précédent dans la table `regulations_cacem`) et insérer les données `old_regulations`  en début de test avant de faire l'update puis vérifier que l'update a eu l'effet escompté.

2024-12-03 10:42 UTC, maximeperraultdev commented on datascience/tests/test_pipeline/test_flows/test_regulations.py
> +def test_update_new_regulations(new_regulations):
yes c'est vrai. Par contre la méthode reset_test_data ne réiniatilise pas la base de données. On rejoue "juste" les fichiers de migrations. Donc j'ai ajouté un `delete` avant mes tests. Tu penses qu'il vaudrait mieux modifier `reset_test_data`pour aller truncate toutes les tables ?

2024-12-04 16:02 UTC, VincentAntoine approved these changes

2024-12-04 16:22 UTC, merged