[MissionSource] Display mission source
MTES-MCT/monitorenv pull request #417
Opened 2023-04-05 06:39 UTC by claire2212

- Resolve #402

- Ajout du tag de la source sur la pop-up de mission
- Ajout d'une colonne et d'un filtre origine dans le tableau des missions
- Ajout du tag de la source dans le header de la page d'une mission

2023-04-05 13:55 UTC, thoomasbro requested changes

2023-04-05 13:55 UTC, thoomasbro commented on frontend/src/features/missions/MissionsList/MissionsTableFilters.tsx
> +        <StyledSelect
Il me semble qu'on doit pouvoir choisir les missions venant du CNSP ***ET*** du CACEM

2023-04-05 13:56 UTC, thoomasbro commented
Pas de problème de linter de mon coté.. étrange

2023-04-06 07:21 UTC, claire2212 commented on frontend/src/features/missions/MissionsList/MissionsTableFilters.tsx
> +        <StyledSelect
@thoomasbro pour avoir les deux il suffit de supprimer le filtrage

2023-04-06 07:56 UTC, thoomasbro commented on frontend/src/features/missions/MissionsList/MissionsTableFilters.tsx
> +        <StyledSelect
à vérifier avec @AdelineCelier mais je pense que ça change la logique par rapport aux autres filtres.

2023-04-06 11:40 UTC, claire2212 commented on frontend/src/features/missions/MissionsList/MissionsTableFilters.tsx
> +        <StyledSelect
@AdelineCelier donc ca veut dire que je laisse le filtre qui permet de ne sélectionner qu'une seule origine?

En fait pour moi comme il n'y a que deux origines possibles je ne vois pas la plus value de pouvoir sélectionner les deux, étant donné que ca donnerait le même résultat que si on ne filtre rien

2023-04-06 15:02 UTC, AdelineCelier commented on frontend/src/features/missions/MissionsList/MissionsTableFilters.tsx
> +        <StyledSelect
Ok je n'ai pas vu ce que ça fait exactement visuellement dans le menu déroulant, mais je suis d'accord avec la logique de dire qu'il ne sert à rien de permettre un filtre sur les deux en même temps.

2023-04-12 07:03 UTC, merged