Add port, mission order & JDP to mission entity
MTES-MCT/monitorenv pull request #421
Opened 2023-04-06 14:15 UTC by ivangabriele

2023-04-06 16:15 UTC, louptheron requested changes
Je propose de bloquer cette PR avant la MEP de Fish, car :
- elle implique pas mal de changements côté Fish (sur les pipelines de données)
- il faut la table des ports dans Env

Après discussion avec @AdelineCelier, on propose de faire une sélection de ports "fake" dans la partie mission, pour faire les tests utilisateurs et continuer sur le reste après

2023-04-19 14:00 UTC, ivangabriele commented
J'ai push-force parce que ça serait bizarre d'amender mon commit originel qui contenait les ports.

2023-04-19 14:15 UTC, ivangabriele commented
Ping @VincentAntoine pour te tenir au courant ^^.

2023-04-20 07:45 UTC, louptheron requested changes

2023-04-20 07:45 UTC, louptheron commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt
> +    @Column(name = "has_mission_order", nullable = false)
Il manquela migration pour `has_mission_order` et `is_under_jdp` non ?

2023-04-20 07:45 UTC, louptheron commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt
> +        hasMissionOrder = hasMissionOrder,
`hasMissionOrder = hasMissionOrder ?: false,` ? et pareil pour `isUnderJdp`

2023-04-20 07:45 UTC, louptheron commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/inputs/CreateOrUpdateMissionDataInput.kt
> +    val isUnderJdp: Boolean? = false
Autant faire comme les autres champs et ne pas rendre nullable `isUnderJdp` : gérer ça dans `MissionModel`

2023-04-20 07:45 UTC, louptheron commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/outputs/MissionDataOutput.kt
> +            val hasMissionOrder = mission.hasMissionOrder ?: false
Et du coup pas besoin de ce check dans l'output

2023-04-21 09:30 UTC, louptheron approved these changes

2023-04-21 09:30 UTC, louptheron commented on backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/outputs/MissionDataOutput.kt
> +    val hasMissionOrder: Boolean? = false,
Du coup il ne peut pas être nullable comme il n'ets pas nullable dans `MissionEntity`

2023-04-21 09:30 UTC, louptheron commented
@thoomasbro Ok pour toi ?

2023-04-21 14:49 UTC, thoomasbro approved these changes

2023-04-21 16:17 UTC, merged