[Missions] Ajout d'onglets pour pouvoir éditer/créer plusieurs misisons
MTES-MCT/monitorenv pull request #615
Opened 2023-06-21 13:11 UTC by claire2212

- Resolve #556

2023-06-26 13:32 UTC, ivangabriele requested changes

2023-06-26 13:32 UTC, ivangabriele commented on frontend/src/domain/use_cases/navigation/deleteTab.ts
> +export const deleteTab = eventKey => async (dispatch, getState) => {
Je renommerais bien `eventKey`, je pensais qu'il s'agissait d'un KeyboardEvent.key.

2023-06-26 13:32 UTC, ivangabriele commented on frontend/src/pages/HomePage.tsx
> +      if ((isFormDirty && missionState) || multiMissionsState.find(mission => mission.isFormDirty)) {
Je le stockerais d'abord dans une variable. Il vaut mieux éviter les "process" exécutés dans des conditions pour simplifier la compréhension.

2023-06-26 15:12 UTC, thoomasbro reviewed
Je n'arrive pas à reproduire de manière systématique, mais quand j'ouvre puis ferme plusieurs missions depuis le tableau puis depuis la carte et que je ferme des onglets, j'ai parfois la modale de confirmation qui s'affiche, parfois non.

J'ai également eu un bug après plusieurs ouvertures/fermetures, tous les onglets étaient fermés, et après un clic sur le bouton éditer d'une mission sur la carte, 2 onglets se sont ouverts.

2023-06-26 15:12 UTC, thoomasbro commented on frontend/src/domain/use_cases/navigation/switchTab.ts
> +    await dispatch(setMissionState(newSelectedMission.mission))
à retirer ? cf. com précédent

2023-06-26 15:12 UTC, thoomasbro commented on frontend/src/domain/use_cases/navigation/switchTab.ts
> +  // We want to save the active form before switching on another
J'ai l'impression qu'on pourrait déjà synchroniser cette slice avec le form, non ?

2023-06-26 16:24 UTC, claire2212 commented on frontend/src/domain/entities/sideWindow.js
> +  MISSION_NEW: '/new-mission/:id',
@ivangabriele @thoomasbro le risque c'est de tomber sur une route d'une nouvelle mission qui est en fait une mission existante, d'où cette différenciation de route

2023-06-26 16:28 UTC, claire2212 commented on frontend/src/domain/use_cases/missions/addMission.ts
> +    .maxBy(filteredNewMission => filteredNewMission.mission.id)
je ne prend le max que des nouvelles missions (d'où le` filter` juste au-dessus) donc il ne devrait pas y avoir de collision d'id

2023-06-26 16:29 UTC, claire2212 commented on frontend/src/domain/use_cases/missions/createOrEditMission.ts
> +          dispatch(setMissionState(undefined))
voir ma réponse au-dessus

2023-06-26 16:29 UTC, claire2212 commented on frontend/src/domain/use_cases/missions/editMission.js
un reliquat j'imagine, je change

2023-06-26 16:29 UTC, claire2212 commented on frontend/src/domain/use_cases/navigation/switchTab.ts
> +    await dispatch(setMissionState(newSelectedMission.mission))
voir ma réponse au-dessus

2023-06-26 16:30 UTC, claire2212 commented on frontend/src/domain/use_cases/navigation/switchTab.ts
> +  // We want to save the active form before switching on another
le form est synchronisé avec le slice `MissionState`

2023-06-26 16:30 UTC, claire2212 commented on frontend/src/domain/use_cases/missions/editMission.js
> +          missions.push(missionFormatted)
ok

2023-06-26 16:30 UTC, claire2212 commented on frontend/src/domain/use_cases/missions/createOrEditMission.ts
> +            dispatch(setMissionState(response.data))
voir ma réponse au-dessus

2023-06-26 16:30 UTC, claire2212 commented on frontend/src/pages/HomePage.tsx
> +      if ((isFormDirty && missionState) || multiMissionsState.find(mission => mission.isFormDirty)) {
ok

2023-06-26 16:31 UTC, claire2212 commented on frontend/src/domain/shared_slices/MultiMissionsState.ts
> +  multiMissionsState: SelectedMission[]
ok

2023-06-26 16:31 UTC, claire2212 commented on frontend/src/domain/shared_slices/MultiMissionsState.ts
> +export const { deleteMissionFromMultiMissionState, setMultiMissionsState } = multiMissionsStateSlice.actions
ok

2023-06-27 05:59 UTC, claire2212 commented on frontend/src/domain/use_cases/missions/editMission.js
> +          await dispatch(setMissionState(newSelectedMission.mission))
voir ma réponse au-dessus

2023-06-27 07:27 UTC, ivangabriele commented on frontend/src/domain/entities/sideWindow.js
> +  MISSION_NEW: '/new-mission/:id',
En effet, ce problème serait résolu si on utilise des UUID ou CUID.

2023-06-27 09:29 UTC, louptheron commented on frontend/src/domain/shared_slices/MultiMissionsState.ts
> +  multiMissionsState: SelectedMission[]
+1

2023-06-27 09:29 UTC, louptheron commented on frontend/src/domain/shared_slices/MultiMissionsState.ts
> +  multiMissionsState: SelectedMission[]
Et `MultiMissionsState` en `MissionsTabsState` ?

2023-06-27 09:29 UTC, louptheron commented on frontend/src/features/SideWindow/SideWindowLauncher.tsx
> +  const isMissionsFormsAreDirty = useMemo(
`hasAtLeastOneMissionFormDirty` ?

2023-06-27 09:29 UTC, louptheron commented on frontend/src/domain/use_cases/missions/editMission.js
> +export const editMission = missionId => (dispatch, getState) => {
J'aime bien le [return early]( https://gomakethings.com/the-early-return-pattern-in-javascript/) quand il y a pas mal de conditions perso.
Aussi, je trouve que sortir dans une fonction (dans le même fichier) un bout de code permet de le documenter, et au final on aboutit à un truc lisible en anglais:
```
if (j'aipasuntruc) {
  alorsjefaisça()

  if (ahouijedoisvérifierça) {
    faisonsça()
  }

  return
}

Sinonjefaisunautretruc()
```
Perso, je me retrouve à pas mal de petites fonctions en bas de mon fichier et ça m'aide à reprendre le code par la suite

2023-06-27 09:29 UTC, louptheron commented on frontend/src/domain/entities/sideWindow.js
> +  MISSION_NEW: '/new-mission/:id',
On a pas déjà le `type` de la mission dans redux ? (`new` ou `edit`) ?
ça va p-e simplifier le code de n'avoir qu'une seule route (il faudra juste chercher `missionPageRoute` et non plus new et/ou edit)

2023-06-30 13:36 UTC, claire2212 commented
@thoomasbro , @ivangabriele , @louptheron 
La refacto est terminée, j'ai passé en resolve tous les commentaires pour que ce soit plus lisible (soit parce que j'ai traité les retours soit parce qu'ils n'ont plus lieu d'être suite à notre point mardi dernier)

Ci-dessous le détail de ce que j'ai fait depuis votre review : 
- Suppression de la route `MISSION_NEW`
- Création d'un id front pour les nouvelles missions (`new-id`) et utilisation de la route `MISSION`
- Suppression du type de mission (je ne me base plus que sur l'id de la mission ou de la route)
- Gestion de la mission active en se basant sur l'index et le multiMissions state (donc suppression de tous les `setMissionState`)

2023-06-30 19:31 UTC, ivangabriele approved these changes
LGTM, good job :)

2023-06-30 19:31 UTC, ivangabriele commented on frontend/src/domain/use_cases/missions/addMission.ts
> +  const maxNewMissionId = _.chain(missions)
Je trouve un peu mieux d'utiliser `lodash/fp` avec des named exports pour le tree-shaking et rester fonctionnel quand c'est facile.

J'utiliserais plutôt un padding start sur le number des IDs générés de manière à tout simplement utiliser : `sortBy(['id'],  missions).reverse()[0].id` (le id non-new seront forcément avant les `new-` avant le reverse).

2023-07-03 09:31 UTC, claire2212 commented on frontend/src/domain/use_cases/missions/addMission.ts
> +  const maxNewMissionId = _.chain(missions)
@ivangabriele j'ai des `numbers` et des `string` dans le tableau donc le `sortBy` ne fonctionne pas. Pour utiliser lodash/fp et le sortBy il faudrait faire un `flow` suivi d'un `map` pour renvoyer les id en string, puis le `sortBy`, et un `last` pour prendre le dernier élément.
Le souci c'est que si on a ouvert en premier une mission en édition, on va recevoir l'id de la mission donc je dois gérer ce cas spécifique. Je ne suis pas sûre que ce soit plus lisible

2023-07-03 09:32 UTC, claire2212 commented on frontend/src/domain/use_cases/missions/addMission.ts
> +  const maxNewMissionId = _.chain(missions)
Après je suis carrément pour utiliser lodash/fp à l'avenir. Si @thoomasbro est ok

2023-07-04 08:41 UTC, thoomasbro approved these changes

2023-07-04 08:41 UTC, thoomasbro commented on frontend/src/utils/getIdTyped.ts
> +export function getIdTyped(id) {
Ajouter le type ?
```suggestion
export function getIdTyped(id: string | undefined) {
```

2023-07-04 08:41 UTC, thoomasbro commented on frontend/src/features/missions/MissionForm/MissionForm.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
vraiment utile ?

2023-07-05 06:36 UTC, merged